routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::view('/', 'welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Rutas administracion
Route::get('/home/administration', 'HomeController@admin')->name('administration');
Route::get('/home/administration/users', 'HomeController@users')->name('users');
Route::get('/home/administration/users/create-user', 'HomeController@createUser')->name('createUser');
Route::delete('/home/administration/users/delete-user/{email}', 'HomeController@deleteUser')->name('deleteUser');
Route::get('/home/administration/users/edit-user/{email}', 'HomeController@editUser')->name('editUser');
Route::post('/home/administration/users/create-user', 'HomeController@saveUser')->name('saveUser');
Route::post('/home/administracion/users/update-user/{email}', 'HomeController@updateUser')->name('updateUser');
// Rutas solicitud
Route::resource('solicitud', 'SolicitudController', [
  'only' => ['create', 'store', 'edit', 'update', 'show', 'destroy']
]);
Route::get('/home/solicitudes/group/{id_group}', 'SolicitudController@showGroup')->name('solicitud.showGroup');
Route::delete('/home/solicitudes/group/{id_group}', 'SolicitudController@destroyGroup')->name('solicitud.destroyGroup');
Route::get('/home/solicitudes', 'SolicitudController@index')->name('solicitudes');
Route::get('/home/solicitudes/redirecttocampus/{shortname}', 'SolicitudController@redirectToCampus')->name('solicitud.redirectToCampus');
Route::get('/consultar-grupos-asignatura-docente','HomeController@consultarGruposAsignaturaDocente')->name('consultarGruposAsignaturaDocente');
Route::get('/ir-crear-solicitud','HomeController@redirigirACrearSolicitud')->name('redirigirCrearSolicitud');
// Rutas CRUD periodo
Route::get('/home/administration/periodos', 'PeriodoController@index')->name('periodos');
Route::get('/home/administration/periodos/create', 'PeriodoController@create')->name('createPeriodo');
Route::post('/home/administration/periodos', 'PeriodoController@store')->name('storePeriodo');

// Rutas CRUD parametros
Route::get('/home/administration/parametros', 'ParametroController@index')->name('parametros');
Route::get('/home/administration/parametros/create', 'ParametroController@create')->name('createParametro');
Route::post('/home/administration/parametros','ParametroController@store')->name('storeParametro');
Route::get('/home/administration/parametros/edit-parametro/{nombre}', 'ParametroController@edit')->name('editParametro');
Route::post('/home/administracion/parametros/update-parametro/{nombre}', 'ParametroController@update')->name('updateParametro');
Route::delete('/home/administration/parametros/delete-user/{nombre}', 'ParametroController@destroy')->name('deleteParametro');
Route::get('/reportes', 'GenerateReports')->name('reportes');

resources/views/solicitudes/consultargruposasignaturadocente.blade.php
@extends('layouts.app2')

@section('content')
  <div class="container cit-content">
    <div class="row align-items-center justify-content-center" style="margin-top:50px">
        <div class="col-md-12">
          @if ($periodo == 'none')
            <div class="alert alert-danger" role="alert">
              Se encuentra inhabilitado el proceso de solicitudes de ambientes electrónicos.
            </div>
          @else
            <p class="font-weight-bold">Período académico: {{ $periodo }}</p>
            <p>Paso 1: Ingrese el email UAO y el código de asignatura para crear la solicitud de actividad de ambientes electrónicos para cursos en las modalidades e-learning (cursos virtuales), b-learning (cursos apoyados por TIC), y el registros de estudiantes en la plataforma.</p>
            <div class="alert alert-danger" role="alert">
              Si usted es Coordinador o Jefe de Departamento, tenga en cuenta que debe diligenciar el formulario una vez por cada asignatura y por cada docente. Es decir, si desea realizar algún tipo de solicitud vinculada a los cursos de su área, deberá rellenar el formulario por cada docente que tenga a cargo. 
            </div>
            <!--
            @if ($errors->any())
              <div class="alert alert-danger">
                  <ul>
                      @foreach ($errors->all() as $error)
                          <li>{{ $error }}</li>
                      @endforeach
                  </ul>
              </div>
            @endif
            -->
            @if(Session::has('message'))
                <div class="alert alert-warning" role="alert">
                {{ Session::get('message') }}
                </div>
            @endif
            <form action="{{ route('redirigirCrearSolicitud') }}" method="GET">
                <div class="form-row"> 
                    <div class="form-group col-md-6">
                        <label for="email">Email Docente</label>
                        <input type="email" name="email" id="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}" placeholder="Ingrese el email institucional" required autofocus>
                        @if ($errors->has('email'))
                          <span class="invalid-feedback">
                              <strong>{{ $errors->first('email') }}</strong>
                          </span>
                        @endif                      
                    </div>
                    <div class="form-group col-md-6">
                        <label for="codigo">Código Asignatura</label>
                        <input type="text" name="codigo" id="codigo" class="form-control{{ $errors->has('codigo') ? ' is-invalid' : '' }}"  value="{{ old('codigo') }}" placeholder="Ingrese código asignatura" required autofocus>
                        @if ($errors->has('codigo'))
                          <span class="invalid-feedback">
                              <strong>{{ $errors->first('codigo') }}</strong>
                          </span>
                        @endif             
                    </div>
                    <button type="submit" class="btn cit-btn cit-btn-sm">Crear la solicitud</button>
                </div>
            </form>
          @endif
        </div>
    </div>
  </div>
@endsection

resources/views/solicitudes/courseisnot.blade.php
@extends('layouts.app2')
@section('content')
    <div class="container cit-content">
        <div class="row justify-content-center" style="margin-top:50px">
            <div class="card shadow cit-dashboard-card">
                <h5 class="card-header">REQUERIMIENTO NO ENCONTRADO</h5>
                <div class="card-body">
                    <h5 class="card-title">Curso no se encuentra en campus.</h5>
                    <p class="card-text">El curso con el shortname {{ $shortname }} no se encuentra en campus.</p>
                    <a href="{{ route('solicitudes') }}" class="btn cit-btn cit-btn-sm">Regresar a solicitudes</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/solicitudes/createsolicitud.blade.php
@extends('layouts.app2')

@section('content')
    <div class="container cit-content">
        <div class="row justify-content-center" style="margin-top:50px">
            <div class="col-md-12">
                <form action="{{ route('solicitud.store') }}" method="POST">
                    @csrf
                    <input type="hidden" name="username" value="{{ $docente['username'] }}">
                    <input type="hidden" name="cod_asignatura" value="{{ $asignatura['codigo'] }}">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="nombreDocenteInput">Nombre</label>
                            <input class="form-control" placeholder="{{ $docente['firstname'] }}" readonly>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="apellidoDocenteInput">Apellido</label>
                            <input class="form-control" placeholder="{{ $docente['lastname'] }}" readonly>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="formGroupExampleInput">Facultad</label>
                            <input name="facultad" class="form-control" id="nombreFacultadInput" name="facultad" type="text" value="{{ $asignatura['facultad'] }}" placeholder="{{ $asignatura['facultad'] }}" readonly>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="formGroupExampleInput">Departamento</label>
                            <input name="departamento" class="form-control" id="nombreDepartamentoInput" type="text" value="{{ $asignatura['departamento'] }}" placeholder="{{ $asignatura['departamento'] }}" readonly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="nameAsignaturaInput">Nombre de la asignatura</label>
                        <input class="form-control" id="nombreAsignaturaInput" type="text" placeholder="{{ $asignatura['nombre'] }}" readonly>
                    </div>
                    <div class="form-group">
                        <p class="font-weight-bold">Paso 2:</p>
                        <p>Estimado docente {{ $docente['firstname'] }}:</p>

                        <p>El código asignatura {{ $asignatura['codigo'] }} tiene los siguientes grupos. Por favor seleccione los grupos y haga click en el botón Enviar la solicitud.</p>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">Grupos</div>
                        <div class="col-sm-10">
                            @php
                            $i=0;
                            $swAlertMessageTaken = false;
                            @endphp
                            @foreach ($grupos as $grupo)
                                @php
                                    $swtaken=false;
                                    foreach ($solicitudes as $s) {
                                        $gruposTaken = $s->grupos;
                                        foreach ($gruposTaken as $grupoTaken) {
                                            if ($grupoTaken->grupo == $grupo) {
                                                $swtaken = true;
                                                $swAlertMessageTaken = true;
                                                break;
                                            }
                                        }
                                    }
                                @endphp
                                @if ($swtaken)
                                    <div class="form-check">
                                        <input class="form-check-input" name="grupos[]" type="checkbox" id="gridCheck{{ $i }}1" value="{{ $grupo }}" disabled>
                                        <label class="form-check-label" for="gridCheck{{ $i }}1">{{ $grupo }}</label>                                
                                    </div>
                                @else
                                    <div class="form-check">
                                        <input class="form-check-input" name="grupos[]" type="checkbox" id="gridCheck{{ $i }}1" value="{{ $grupo }}">
                                        <label class="form-check-label" for="gridCheck{{ $i }}1">{{ $grupo }}</label>                                
                                    </div>
                                @endif
                                @php $i++; @endphp
                            @endforeach
                        </div>
                    </div>
                    @if ($swAlertMessageTaken)
                      <div class="form-group">
                          <div class="alert alert-warning" role="alert">
                              Los grupos inhabilitados ya se encuentra solicitado por otro docente. Comuniquese con el CIT extensión 12420 para cualquier inquietud.
                          </div>
                      </div>
                    @endif
                    <button type="submit" id="btn" class="btn cit-btn cit-btn-sm" disabled>Enviar solicitud</button>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scriptjs')
<script type="text/javascript">
  $( document ).ready(function() {
    var checkboxes = $("input[type='checkbox']"),
    submitButt = $("button[type='submit']");

    checkboxes.click(function() {
        submitButt.attr("disabled", !checkboxes.is(":checked"));
    });
  });
</script>
@endsection

resources/views/solicitudes/deletesolicitud.blade.php
@extends('layouts.app')

@section('content')
<div class="container cit-content">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">ELIMINAR SOLICITUD</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('solicitud.destroy', ['id_solicitud' => $solicitud->id ]) }}">
                        @csrf
                        @method('DELETE')
                        <input type="hidden" value="1" name="prueba">
                        <div class="form-group row">
                            <label for="id" class="col-md-4 col-form-label text-md-right">{{ __('id') }}</label>
                            <div class="col-md-6">
                                <input id="id" class="form-control{{ $errors->has('id') ? ' is-invalid' : '' }}" name="id" value="{{ $solicitud->id }}" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('username') }}</label>
                            <div class="col-md-6">
                                <input id="username" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" value="{{ $solicitud->username }}" name="username" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="codigo_asignatura" class="col-md-4 col-form-label text-md-right">{{ __('codigo_asignatura') }}</label>
                            <div class="col-md-6">
                                <input id="codigo_asignatura" class="form-control{{ $errors->has('codigo_asignatura') ? ' is-invalid' : '' }}" value="{{ $solicitud->codigo_asignatura }}" name="codigo_asignatura" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="modalidad" class="col-md-4 col-form-label text-md-right">{{ __('modalidad') }}</label>
                            <div class="col-md-6">
                                <input 
                                    id="modalidad"
                                    class="form-control{{ $errors->has('modalidad') ? ' is-invalid' : '' }}"
                                    value="{{ $solicitud->modalidad }}"
                                    name="modalidad" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="facultad" class="col-md-4 col-form-label text-md-right">{{ __('facultad') }}</label>
                            <div class="col-md-6">
                                <input id="facultad" class="form-control{{ $errors->has('facultad') ? ' is-invalid' : '' }}" value="{{ $solicitud->facultad }}" name="facultad" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="departamento" class="col-md-4 col-form-label text-md-right">{{ __('departamento') }}</label>
                            <div class="col-md-6">
                                <input id="departamento" class="form-control{{ $errors->has('departamento') ? ' is-invalid' : '' }}" value="{{ $solicitud->departamento }}" name="departamento" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="state" class="col-md-4 col-form-label text-md-right">{{ __('estado') }}</label>
                            <div class="col-md-6">
                                <input id="state" class="form-control{{ $errors->has('state') ? ' is-invalid' : '' }}" value="{{ $solicitud->state }}" name="state" required readonly>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4 alert alert-danger" role="alert">
                                !Ingrese ELIMINAR para confirmar!
                                <input id="txtConfirmacion" type="text" class="form-control" onkeyUP="validate()">
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button id="btnsubmit" type="submit" class="btn btn-outline-danger" disabled>ELIMINAR</button>
                                <a class="btn btn-primary" href={{ route('solicitudes')}} role="button">Cancelar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div> <!-- card -->
        </div> <!-- col-md-8 --> 
    </div>
</div>
@endsection
<script src="{{ asset('js/custom.js') }}"></script>

resources/views/solicitudes/editsolicitud.blade.php
@extends('layouts.app')

@section('content')
<div class="container cit-content">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Actualizar solicitud</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('solicitud.update', ['id_solicitud' => $solicitud->id ]) }}">
                        @csrf
                        @method('PUT')
                        <input type="hidden" value="1" name="prueba">
                        <div class="form-group row">
                            <label for="id" class="col-md-4 col-form-label text-md-right">{{ __('id') }}</label>
                            <div class="col-md-6">
                                <input id="id" class="form-control{{ $errors->has('id') ? ' is-invalid' : '' }}" name="id" value="{{ $solicitud->id }}" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="username" class="col-md-4 col-form-label text-md-right">{{ __('username') }}</label>
                            <div class="col-md-6">
                                <input id="username" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" value="{{ $solicitud->username }}" name="username" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="codigo_asignatura" class="col-md-4 col-form-label text-md-right">{{ __('codigo_asignatura') }}</label>
                            <div class="col-md-6">
                                <input id="codigo_asignatura" class="form-control{{ $errors->has('codigo_asignatura') ? ' is-invalid' : '' }}" value="{{ $solicitud->codigo_asignatura }}" name="codigo_asignatura" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="modalidad" class="col-md-4 col-form-label text-md-right">{{ __('modalidad') }}</label>
                            <div class="col-md-6">
                                <input 
                                    id="modalidad"
                                    class="form-control{{ $errors->has('modalidad') ? ' is-invalid' : '' }}"
                                    value="{{ $solicitud->modalidad }}"
                                    name="modalidad" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="facultad" class="col-md-4 col-form-label text-md-right">{{ __('facultad') }}</label>
                            <div class="col-md-6">
                                <input id="facultad" class="form-control{{ $errors->has('facultad') ? ' is-invalid' : '' }}" value="{{ $solicitud->facultad }}" name="facultad" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="departamento" class="col-md-4 col-form-label text-md-right">{{ __('departamento') }}</label>
                            <div class="col-md-6">
                                <input id="departamento" class="form-control{{ $errors->has('departamento') ? ' is-invalid' : '' }}" value="{{ $solicitud->departamento }}" name="departamento" required readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="state" class="col-md-4 col-form-label text-md-right">{{ __('estado') }}</label>
                            <div class="col-md-6">
                                <select  id="state" class="form-control" name="state">
                                    <option @if ($solicitud->state == '0') selected @endif value="0">Sin procesar</option>
                                    <option @if ($solicitud->state == '1') selected @endif value="1">Espacio creado</option>
                                    <option @if ($solicitud->state == '2') selected @endif value="2">Matriculado</option>
                                    <option @if ($solicitud->state == '3') selected @endif value="3">Actualizando</option>
                                    <option @if ($solicitud->state == '4') selected @endif value="4">Validado</option>
                                    <option @if ($solicitud->state == '5') selected @endif value="5">Pausado</option>
                                    <option @if ($solicitud->state == '6') selected @endif value="6">Error</option>
                                    <option @if ($solicitud->state == '7') selected @endif value="7">Sin actualizar</option>
                                    <option @if ($solicitud->state == '8') selected @endif value="8">Desmatricular</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">Actualizar</button>
                                <button class="btn btn-primary">Cancelar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/solicitudes/index.blade.php
@extends('layouts.app')

@section('content')
    {{-- breadcrumb --}}
    <div class="container cit-content">
        <div class="row justify-content-center no-gutters">
            <div class="col-md-10">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent">
                <li class="breadcrumb-item"><a href={{ route('home') }} class="text-dark">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Solicitudes</li>
                </ol>
            </nav>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row pt-sm-3">
            <div class="col-md-12 d-flex justify-content-center">
                <p class="h4">solicitudes {{ $periodo_actual }}</p>
            </div>
        </div>
        <div class="row pt-sm-3">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col" style="width: 2%">#</th>
                                <th scope="col" style="width: 20%"><i class="fas fa-user"></i></th>
                                <th scope="col" style="width: 10%"><i class="fas fa-book"></i></th>
                                <th scope="col" style="width: 10%">modalidad</th>
                                <th scope="col" style="width: 20%"><i class="fas fa-users"></i></th>
                                <th scope="col" style="width: 10%"><i class="fas fa-battery-three-quarters"></i></th>
                                <th scope="col" style="width: 10%"><i class="fas fa-calendar-alt"></i></th>
                                <th scope="col" style="width: 10%"><i class="fas fa-hourglass-end"></i></th>
                                <th scope="col" colspan="3" style="width: 8%">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $i=1;
                            @endphp
                            @foreach ($solicitudes as $solicitud)
                                <tr>
                                    <th scope="row" class="table-light">{{ $solicitud->id }}</th>
                                    <td class="table-light">{{ $solicitud->username }}</td>
                                    <td class="table-light">{{ $solicitud->codigo_asignatura }}</td>
                                    <td class="table-light">{{ $solicitud->modalidad }}</td>
                                    <td class="table-light">
                                        @foreach ($solicitud->grupos as $g)
                                            <a href={{ route('solicitud.showGroup', ['id_group' => $g->id]) }}>{{ $g->grupo }}</a>
                                        @endforeach
                                    </td>
                                    
                                    @switch($solicitud->state)
                                        @case(0)
                                            <td class="table-light"><i class="fas fa-sign-in-alt"></i></i></td>
                                            @break
                                        @case(1)
                                            <td class="table-light"><i class="fas fa-building"></i></td>
                                            @break
                                        @case(2)
                                            <td class="table-light"><i class="fas fa-clipboard-check"></i></td>
                                            @break
                                        @case(3)
                                            <td class="table-light"><i class="fas fa-sync"></i></td>
                                            @break
                                        @case(4)
                                            <td class="table-light"><i class="far fa-smile"></i></td>
                                            @break
                                        @case(5)
                                            <td class="table-light"><i class="fas fa-pause"></i></td>
                                            @break
                                        @case(6)
                                            <td class="table-light"><i class="fas fa-exclamation"></i></td>
                                            @break
                                        @case(7)
                                            <td class="table-light"><i class="fas fa-upload"></i></td>
                                            @break
                                        @case(8)
                                            <td class="table-light"><i class="fas fa-eraser"></i></td>
                                            @break

                                    @endswitch
                                    <td class="table-light">{{ $solicitud->fecha_solicitud }}</td>
                                    @if ($solicitud->fecha_procesamiento == null )
                                        <td class="table-light"><i class="far fa-clock"></i></td>
                                    @else
                                        <td class="table-light">{{ $solicitud->fecha_procesamiento }}</td>
                                    @endif
                                    <td class="actions"><a href={{ route('solicitud.redirectToCampus', ['shortname' => $solicitud->codigo_asignatura.'-'.$solicitud->username.'-'.$solicitud->modalidad ]) }} target="_blank"><i class="fas fa-university"></i></a></td>
                                    <td class="actions"><a href={{ route('solicitud.edit', ['id_solicitud' => $solicitud->id])}} class="icon"><i class="far fa-edit"></i></a></td>
                                    <td class="actions"><a href={{ route('solicitud.show', ['id_solicitud' => $solicitud->id])}} class="icon"><i class="fas fa-trash"></i></a></td>
                                </tr>
                                @php
                                    $i++;
                                @endphp
                            @endforeach
                        </tbody>
                    </table>
                </div> <!-- table -->
            </div> <!-- col -->
        </div> <!-- row -->
    </div> <!-- container -->
@endsection

resources/views/solicitudes/successtore.blade.php
@extends('layouts.app2')

@section('content')
    <div class="container cit-content">
        <div class="row justify-content-center" style="margin-top:50px">
            <div class="card shadow cit-dashboard-card">
                <h5 class="card-header">Activación y matriculación</h5>
                <div class="card-body">
                    <h5 class="card-title">Enviado satisfactoriamente</h5>
                    <p class="card-text">Su solicitud ha sido registrada en el sistema.</p>
                    <a href="{{ route('consultarGruposAsignaturaDocente') }}" class="btn cit-btn cit-btn-sm">Activar otro curso</a>
                </div>
            </div>
        </div>
    </div>
@endsection